import os.path as opath
from sys import path as spath
spath.append(opath.join(opath.dirname(__file__), '../lib'))
from mitie import *


class Sentence():
    """A class for sentence metadata.

    Attributes:
        text: A string of the sentence text.
        offset_list: A list storing the offset of each character in the
            sentence.
        tokens: A list of tokens generated by the MITIE tokenizer.
        entities: A list of tuples storing the range and type of the entities.
    """

    def __init__(self, text, offset_list):
        self.text = text
        self.offset_list = offset_list
        self.tokens = tokenize(text.lower())  # using MITIE tokenizer
        self.entities = []

    def get_begin(self):
        return self.offset_list[0]

    def get_end(self):
        return self.offset_list[-1]

    def has_entity(self):
        return len(self.entities) > 0

    def add_entity(self, token_range, entity_type):
        """Adds an entity to the Sentence object.

        Args:
            token_range: A xrange object indicating the start and end token
                number of the entity.
            entity_type: A string indicating the type of the entity.
        """
        self.entities.append((token_range, entity_type))
